### PR TITLE
build: bump "forge-std"

### PR DESCRIPTION
**Pull request by PaulRBerg**
Bumps `forge-std` to [v1.5.2](https://github.com/foundry-rs/forge-std/releases/tag/v1.5.2).

### CODE REVIEW

**Comment by mds1** [comment]
Just wondering why do we need the forge-std bump? Is having different forge-std versions in deps interfering with something?

**Comment by PaulRBerg** [comment]
No, no dependency interference. The goal is to speed up the install time when cloning my project with `--recurse-submodules` 😅

**Comment by mds1** [comment]
That means it will slow down install time for users with projects pinned to other versions of forge-std 😉

I'll merge this version bump since there's no harm, but would like to avoid future PRs like this unless necessary since there's not much net benefit to them

**Comment by PaulRBerg** [comment]
> pinned to other versions of forge-std

Yes, but the `v1` branch is a Schelling point. [Version tags cannot be pinned in `.gitmodules`](https://github.com/foundry-rs/foundry/issues/4155).

> I'll merge this version bump since there's no harm

Thanks

> but would like to avoid future PRs like this unless necessary since there's not much net benefit to them

Sure thing

**Comment by mds1** [comment]
> Yes, but the `v1` branch is a Schelling point

In theory I agree, in practice I'm pretty sure most repos don't use it and don't update forge-std frequently (based on some recent sourcegrah searches). Either way no big deal and appreciate your PRs! 🙂

**Pull request merged**
